[project]
name = "local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyboard>=0.13.5",
    "opencv-python>=4.11.0.86",
    "pygame>=2.6.1",
    "websockets>=15.0.1",
]
